version: '3.9'

services:
  app:
    container_name: shogi_app
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./backend/
        target: /myapp/
    command: rails server -b 0.0.0.0
  front:
    container_name: shogi_front
    build:
      dockerfile: docker/front/Dockerfile
      context: .
    ports:
      - '3001:3001'
    volumes:
      - type: bind
        source: ./frontend/
        target: /myfront/
    command: yarn dev